################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../advertisement.c \
../app.c \
../app_hw.c \
../app_ui.c \
../application_properties.c \
../beacon.c \
../gatt_db.c \
../graphics.c \
../htm.c \
../ia.c \
../init_app.c \
../init_board.c \
../init_mcu.c \
../main.c \
../pti.c 

OBJS += \
./advertisement.o \
./app.o \
./app_hw.o \
./app_ui.o \
./application_properties.o \
./beacon.o \
./gatt_db.o \
./graphics.o \
./htm.o \
./ia.o \
./init_app.o \
./init_board.o \
./init_mcu.o \
./main.o \
./pti.o 

C_DEPS += \
./advertisement.d \
./app.d \
./app_hw.d \
./app_ui.d \
./application_properties.d \
./beacon.d \
./gatt_db.d \
./graphics.d \
./htm.d \
./ia.d \
./init_app.d \
./init_board.d \
./init_mcu.d \
./main.d \
./pti.d 


# Each subdirectory must supply rules for building sources it contributes
advertisement.o: ../advertisement.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"advertisement.d" -MT"advertisement.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app.o: ../app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"app.d" -MT"app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app_hw.o: ../app_hw.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"app_hw.d" -MT"app_hw.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app_ui.o: ../app_ui.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"app_ui.d" -MT"app_ui.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

application_properties.o: ../application_properties.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"application_properties.d" -MT"application_properties.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

beacon.o: ../beacon.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"beacon.d" -MT"beacon.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gatt_db.o: ../gatt_db.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"gatt_db.d" -MT"gatt_db.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

graphics.o: ../graphics.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"graphics.d" -MT"graphics.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

htm.o: ../htm.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"htm.d" -MT"htm.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

ia.o: ../ia.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"ia.d" -MT"ia.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_app.o: ../init_app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"init_app.d" -MT"init_app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_board.o: ../init_board.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"init_board.d" -MT"init_board.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_mcu.o: ../init_mcu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"init_mcu.d" -MT"init_mcu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

main.o: ../main.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"main.d" -MT"main.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pti.o: ../pti.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__NO_SYSTEM_INIT=1' '-DEFR32BG1B232F256GM56=1' -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\CMSIS\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\bsp" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\app\bluetooth_2.6\common\stack_bridge" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emlib\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\bootloader\api" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\drivers" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\display" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd\ssd2119" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\soc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\EFR32BG1_BRD4303A\config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\hardware\kit\common\halconfig" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\radio\rail_lib\chip\efr32" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\uartdrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\common\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\protocol\bluetooth_2.6\ble_stack\inc\common" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\sleep\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\halconfig\inc\hal-config" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\middleware\glib\dmd" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\dmadrv\src" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\emdrv\gpiointerrupt\inc" -I"G:\My Drive\R&D\Firmware Design\KHS2\KHS2\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -O2 -fno-short-enums -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=hard -MMD -MP -MF"pti.d" -MT"pti.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


